# Generated by Django 5.1 on 2024-08-15 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default=True, upload_to='Productos/', verbose_name='Imagen de Productos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorias',
            name='visibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='disponibilidad',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='visibilidad',
            field=models.BooleanField(default=True),
        ),
    ]
