# Generated by Django 5.1 on 2024-08-16 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_producto_imagen_alter_categorias_visibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='preciodesceunto',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, help_text='Porciento de descuento para este producto, ejemplo: 15%', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
