# Generated by Django 5.1 on 2024-08-16 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_producto_preciodesceunto_alter_producto_descuento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciodesceunto',
            field=models.FloatField(editable=False),
        ),
    ]
