# Generated by Django 5.1 on 2024-08-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_alter_producto_precio_alter_producto_preciodesceunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='preciodesceunto',
            new_name='preciodescuento',
        ),
    ]
