# Generated by Django 5.1 on 2024-08-16 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0005_rename_preciodesceunto_producto_preciodescuento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.IntegerField(blank=True, default=0, help_text='Porciento de descuento para este producto, ejemplo: 15%', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='preciodescuento',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
